name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
    
                
    - name: Check if executable exists
      shell: bash
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        executable_name="stack_overflow"
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          executable_name="Release/${executable_name}.exe"
        fi
    
        # Check if the executable exists
        if [ -f "$executable_name" ]; then
          echo "Executable exists: $executable_name"
        else
          echo "Executable not found!"
          exit 1
        fi
    
    - name: Run executable and check output format
      shell: bash
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        executable_name="stack_overflow"
        
        # Check if we are running on Windows
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          executable_name="{executable_name}.exe"
        fi
        
        echo "Full executable path: $executable_name"
    
        # Check if the executable exists
        if [ -f "$executable_name" ]; then
          echo "Executable exists: $executable_name"
        else
          echo "Executable not found!"
          exit 1
        fi
        
        # Try to run it if it exists
        echo "Running $executable_name"
        
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          # On Windows, we run the executable from the Release directory
          ./Release/$executable_name > app_output.txt
        else
          # For non-Windows platforms, we just use the executable name
          ./$executable_name > app_output.txt
        fi
